// Generated by Selenium IDE
import org.junit.*;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.sql.Driver;
import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AuthorizationTest {
  private static WebDriver driver;
  private WebDriverWait wait;
  private static Map<String, Object> vars;
  private static JavascriptExecutor js;
  private static Properties properties = new Reader().getProperties();

  @BeforeClass
  public static void setUp() {
    if (properties.getBrowser().toLowerCase().equals("chrome"))
      driver = new ChromeDriver();
    else {
      System.setProperty("webdriver.gecko.driver", "/home/maximyarosh/Загрузки/geckodriver");
      driver = new FirefoxDriver();
    }
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(40));
    driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(20));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterClass
  public static void tearDown() {
    driver.close();
  }

  @Test
  public void authorizationTest() {
    driver.get(properties.getUrl());
    driver.manage().window().setSize(new Dimension(1920, 1080));
    WebElement signUpButton = driver.findElement(By.xpath("/html/body/div[1]/div/div[5]/div[2]/header/nav/div/div[4]/button"));
    signUpButton.click();
    WebElement byEmailButton = driver.findElement(By.xpath("/html/body/div[1]/div/div[5]/div[2]/header/nav/div/div[2]/div/div[2]/div[2]/div[7]/a"));
    byEmailButton.click();
    WebElement nameInput = driver.findElement(By.xpath("//*[@id=\"register-field--name\"]"));
    nameInput.sendKeys(properties.getName());
    WebElement emailInput = driver.findElement(By.xpath("//*[@id=\"register-field--email\"]"));
    emailInput.sendKeys(properties.getLogin());
    WebElement passwordInput = driver.findElement(By.xpath("//*[@id=\"register-field--password\"]"));
    passwordInput.sendKeys(properties.getPassword());

  }
}
